plugins {
    id 'com.android.application'
}

def keystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
def keystorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
def keyAliasValue = System.getenv("ANDROID_KEY_ALIAS")
def keyPasswordValue = System.getenv("ANDROID_KEY_PASSWORD")

android {
    namespace 'de.fachteilluchs.app'
    compileSdk 35

    defaultConfig {
        applicationId 'de.fachteilluchs.app'
        minSdk 24
        targetSdk 35
        versionCode 17
        versionName '2.0.2'
    }

    signingConfigs {
        release {
            if (keystorePath && keystorePassword && keyAliasValue && keyPasswordValue) {
                storeFile file(keystorePath)
                storePassword keystorePassword
                keyAlias keyAliasValue
                keyPassword keyPasswordValue
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }

        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
